declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'SERVICE-ENDPOINT-PROD-CONFIGS'"
  method: post
  accepts: json
  returns: json
  namespace: service

assign_step:
  assign:
    sensitive:
      api_key: '112218ssQQ212Prod'
      username: 'User100'
      password: 'pwd158'

return_value:
  wrapper: false
  return: ${sensitive}
