declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'SERVICES'"
  method: get
  accepts: json
  returns: json
  namespace: service

get_services_list:
  call: http.post
  args:
    url: "[#SERVICE_RESQL]/get-services-list"
  result: services_res

assign_services_result:
  assign: 
    services: ${services_res.response.body}

get_approved_triggers:
  call: http.post
  args:
    url: "[#SERVICE_TRAINING_RESQL]/get-approved-tiggers"
  result: triggers_res

assign_training_result:
  assign: 
    triggers: ${triggers_res.response.body}

return_ok:
  status: 200
  return: ${[services, triggers]}
  next: end
