declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'SERVICE-ENDPOINT-TEST-CONFIGS'"
  method: get
  accepts: json
  returns: json
  namespace: service

assign_step:
  assign:
    sensitive:
      api_key: '112218ssQQ212TEST'
      username: 'User20'
      password: 'pwd18'

return_value:
  wrapper: false
  return: ${sensitive}
