FROM node:22-alpine

RUN addgroup -S nonroot \
    && adduser -S nonroot -G nonroot

USER nonroot

ENV PORT=3001

WORKDIR /app
COPY ./package.json .
RUN npm install --legacy-peer-deps --ignore-scripts

COPY . .

EXPOSE ${PORT}

CMD ["npm", "run", "dev"]
