import { FC, PropsWithChildren, useMemo, useState } from 'react';
import { Assign } from 'types';
import { getTypeColor } from 'utils/object-util';

import {
  type BaseDate,
  createDateTimeDragData,
  type DatePart,
  type FormatOptions,
  type FormatType,
  generateDateCode,
  type Separator,
} from './date-time-utils';
import { DateTimeBuilderContext, type DateTimeBuilderContextValue } from './DateTimeBuilderContext';

interface DateTimeBuilderProviderProps extends PropsWithChildren {}

export const DateTimeBuilderProvider: FC<DateTimeBuilderProviderProps> = ({ children }) => {
  const [base, setBase] = useState<BaseDate>('now');
  const [days, setDays] = useState<string>('0');
  const [months, setMonths] = useState<string>('0');
  const [years, setYears] = useState<string>('0');
  const [isTimePrecisionEnabled, setIsTimePrecisionEnabled] = useState<boolean>(false);
  const [time, setTime] = useState<string>('21:00:00.000');
  const [formatType, setFormatType] = useState<FormatType>('dateOnly');
  const [dateOrder, setDateOrder] = useState<[DatePart, DatePart, DatePart]>(['YYYY', 'MM', 'DD']);
  const [separator, setSeparator] = useState<Separator>('-');

  const formatOptions: FormatOptions = useMemo(
    () => ({
      type: formatType,
      ...(formatType !== 'yearOnly' ? { dateOrder, separator } : {}),
    }),
    [formatType, dateOrder, separator],
  );

  const dateCode = useMemo(
    () =>
      generateDateCode(base, {
        days,
        months,
        years,
        isTimePrecisionEnabled,
        time,
        format: formatOptions,
      }),
    [base, days, months, years, isTimePrecisionEnabled, time, formatOptions],
  );

  const dragData: Assign = useMemo(() => createDateTimeDragData(dateCode), [dateCode]);

  const evaluatedDate = useMemo(() => {
    // Evaluate the dateCode JavaScript to get the actual date string
    // Safe to execute: dateCode is generated by our own generateDateCode function
    // which only creates date manipulation code from controlled inputs, never user-provided strings
    // eslint-disable-next-line sonarjs/code-eval
    const result = new Function(`return ${dateCode}`)() as string;
    return result;
  }, [dateCode]);

  const borderColor = useMemo(() => getTypeColor(dateCode).color, [dateCode]);

  const value: DateTimeBuilderContextValue = useMemo(
    () => ({
      state: {
        base,
        days,
        months,
        years,
        isTimePrecisionEnabled,
        time,
        formatType,
        dateOrder,
        separator,
      },
      setBase,
      setDays,
      setMonths,
      setYears,
      setIsTimePrecisionEnabled,
      setTime,
      setFormatType,
      setDateOrder,
      setSeparator,
      formatOptions,
      dateCode,
      dragData,
      evaluatedDate,
      borderColor,
    }),
    [
      base,
      days,
      months,
      years,
      isTimePrecisionEnabled,
      time,
      formatType,
      dateOrder,
      separator,
      formatOptions,
      dateCode,
      dragData,
      evaluatedDate,
      borderColor,
    ],
  );

  return <DateTimeBuilderContext.Provider value={value}>{children}</DateTimeBuilderContext.Provider>;
};
