import OutputElementBox from 'components/OutputElementBox';
import Track from 'components/Track';
import { CSSProperties, FC, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Assign } from 'types';
import { getTypeColor } from 'utils/object-util';

import {
  type BaseDate,
  createDateTimeDragData,
  type DatePart,
  type FormatOptions,
  type FormatType,
  generateDateCode,
  type Separator,
} from './date-time-utils';
import DateSettings from './DateSettings';
import FormatSettings from './FormatSettings';

interface DateTimeBuilderProps {
  border: string;
  popupBodyCss: CSSProperties;
}

const DateTimeBuilder: FC<DateTimeBuilderProps> = ({ border, popupBodyCss }) => {
  const { t } = useTranslation();
  const [base, setBase] = useState<BaseDate>('now');
  const [days, setDays] = useState<string>('0');
  const [months, setMonths] = useState<string>('0');
  const [years, setYears] = useState<string>('0');
  const [isTimePrecisionEnabled, setIsTimePrecisionEnabled] = useState<boolean>(false);
  const [time, setTime] = useState<string>('21:00:00.000');
  const [formatType, setFormatType] = useState<FormatType>('dateOnly');
  const [dateOrder, setDateOrder] = useState<[DatePart, DatePart, DatePart]>(['YYYY', 'MM', 'DD']);
  const [separator, setSeparator] = useState<Separator>('-');

  const formatOptions: FormatOptions = useMemo(
    () => ({
      type: formatType,
      ...(formatType !== 'yearOnly' ? { dateOrder, separator } : {}),
    }),
    [formatType, dateOrder, separator],
  );

  const dateCode = useMemo(
    () =>
      generateDateCode(base, {
        days,
        months,
        years,
        isTimePrecisionEnabled,
        time,
        format: formatOptions,
      }),
    [base, days, months, years, isTimePrecisionEnabled, time, formatOptions],
  );

  const dragData: Assign = useMemo(() => createDateTimeDragData(dateCode), [dateCode]);

  const evaluatedDate = useMemo(() => {
    // Evaluate the dateCode JavaScript to get the actual date string
    // Safe to execute: dateCode is generated by our own generateDateCode function
    // which only creates date manipulation code from controlled inputs, never user-provided strings
    // eslint-disable-next-line sonarjs/code-eval
    const result = new Function(`return ${dateCode}`)() as string;
    return result;
  }, [dateCode]);

  return (
    <Track
      direction="vertical"
      align="left"
      style={{
        ...popupBodyCss,
        borderBottom: border,
      }}
    >
      <label htmlFor="json" style={{ marginBottom: '10px' }}>
        {t('serviceFlow.previousVariables.dateAndTime.title')}
      </label>

      <Track direction="horizontal" align="center" gap={8} style={{ width: '100%', flexWrap: 'wrap' }}>
        <OutputElementBox
          dragData={dragData}
          borderColor={getTypeColor(dateCode).color}
          style={{ cursor: 'grab', width: 'fit-content' }}
        >
          {t('serviceFlow.previousVariables.dateAndTime.title')}
        </OutputElementBox>
        <span style={{ fontSize: '12px', color: '#666', fontFamily: 'monospace' }}>{evaluatedDate}</span>
      </Track>

      <Track direction="horizontal" align="stretch" gap={16} style={{ width: '100%' }}>
        <DateSettings
          base={base}
          days={days}
          months={months}
          years={years}
          isTimePrecisionEnabled={isTimePrecisionEnabled}
          time={time}
          onBaseChange={setBase}
          onDaysChange={setDays}
          onMonthsChange={setMonths}
          onYearsChange={setYears}
          onTimePrecisionToggle={() => setIsTimePrecisionEnabled(!isTimePrecisionEnabled)}
          onTimeChange={setTime}
        />

        <FormatSettings
          formatType={formatType}
          dateOrder={dateOrder}
          separator={separator}
          onFormatTypeChange={setFormatType}
          onDateOrderChange={setDateOrder}
          onSeparatorChange={setSeparator}
        />
      </Track>
    </Track>
  );
};

export default DateTimeBuilder;
