import FormCheckbox from 'components/FormElements/FormCheckbox';
import FormInput from 'components/FormElements/FormInput';
import FormSelect from 'components/FormElements/FormSelect';
import OutputElementBox from 'components/OutputElementBox';
import Track from 'components/Track';
import { CSSProperties, FC, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Assign } from 'types';
import { getTypeColor } from 'utils/object-util';

import {
  type BaseDate,
  createDateTimeDragData,
  type DatePart,
  type FormatOptions,
  type FormatType,
  generateDateCode,
  getBaseOptions,
  type Separator,
} from './date-time-utils';

interface DateTimeBuilderProps {
  border: string;
  popupBodyCss: CSSProperties;
}

const DateTimeBuilder: FC<DateTimeBuilderProps> = ({ border, popupBodyCss }) => {
  const { t } = useTranslation();
  const [base, setBase] = useState<BaseDate>('now');
  const [days, setDays] = useState<string>('0');
  const [months, setMonths] = useState<string>('0');
  const [years, setYears] = useState<string>('0');
  const [isTimePrecisionEnabled, setIsTimePrecisionEnabled] = useState<boolean>(false);
  const [time, setTime] = useState<string>('21:00:00.000');
  const [formatType, setFormatType] = useState<FormatType>('dateOnly');
  const [dateOrder, setDateOrder] = useState<[DatePart, DatePart, DatePart]>(['YYYY', 'MM', 'DD']);
  const [separator, setSeparator] = useState<Separator>('-');

  const formatOptions: FormatOptions = useMemo(
    () => ({
      type: formatType,
      ...(formatType === 'dateOnly' ||
      formatType === 'custom' ||
      formatType === 'timestamp' ||
      formatType === 'timestampMs'
        ? { dateOrder, separator }
        : {}),
    }),
    [formatType, dateOrder, separator],
  );

  const dateCode = useMemo(
    () =>
      generateDateCode(base, {
        days,
        months,
        years,
        isTimePrecisionEnabled,
        time,
        format: formatOptions,
      }),
    [base, days, months, years, isTimePrecisionEnabled, time, formatOptions],
  );

  const dragData: Assign = useMemo(() => createDateTimeDragData(dateCode), [dateCode]);

  const evaluatedDate = useMemo(() => {
    // Evaluate the dateCode JavaScript to get the actual date string
    // Safe to execute: dateCode is generated by our own generateDateCode function
    // which only creates date manipulation code from controlled inputs, never user-provided strings
    // eslint-disable-next-line sonarjs/code-eval
    const result = new Function(`return ${dateCode}`)() as string;
    return result;
  }, [dateCode]);

  return (
    <Track
      direction="vertical"
      align="left"
      style={{
        ...popupBodyCss,
        borderBottom: border,
      }}
    >
      <label htmlFor="json" style={{ marginBottom: '10px' }}>
        {t('serviceFlow.previousVariables.dateAndTime.title')}
      </label>

      <Track direction="horizontal" align="center" gap={8} style={{ width: '100%', flexWrap: 'wrap' }}>
        <OutputElementBox
          dragData={dragData}
          borderColor={getTypeColor(dateCode).color}
          style={{ cursor: 'grab', width: 'fit-content' }}
        >
          {t('serviceFlow.previousVariables.dateAndTime.title')}
        </OutputElementBox>
        <span style={{ fontSize: '12px', color: '#666', fontFamily: 'monospace' }}>{evaluatedDate}</span>
      </Track>

      <Track direction="horizontal" align="stretch" gap={16} style={{ width: '100%' }}>
        <Track direction="vertical" align="stretch" gap={16} style={{ flex: '0 0 50%', maxWidth: '50%' }}>
          <label style={{ fontSize: '14px', fontWeight: 500 }}>
            {t('serviceFlow.previousVariables.dateAndTime.base')}
          </label>
          <FormSelect
            label=""
            name="base"
            hideLabel
            options={getBaseOptions()}
            defaultValue={base}
            style={{ fontSize: '14px', width: '100%', maxWidth: '100%' }}
            onSelectionChange={(selection) => {
              if (selection) {
                setBase(selection.value as BaseDate);
              }
            }}
          />

          <label style={{ fontSize: '14px', fontWeight: 500 }}>
            {t('serviceFlow.previousVariables.dateAndTime.offset')}
          </label>
          <Track direction="vertical" align="stretch" gap={8}>
            <FormInput
              label={String(t('serviceFlow.previousVariables.dateAndTime.days'))}
              name="days"
              type="number"
              value={days}
              onChange={(e) => setDays(e.target.value)}
              style={{ width: '100%', maxWidth: '100%' }}
            />
            <FormInput
              label={String(t('serviceFlow.previousVariables.dateAndTime.months'))}
              name="months"
              type="number"
              value={months}
              onChange={(e) => setMonths(e.target.value)}
              style={{ width: '100%', maxWidth: '100%' }}
            />
            <FormInput
              label={String(t('serviceFlow.previousVariables.dateAndTime.years'))}
              name="years"
              type="number"
              value={years}
              onChange={(e) => setYears(e.target.value)}
              style={{ width: '100%', maxWidth: '100%' }}
            />
          </Track>

          <label style={{ fontSize: '14px', fontWeight: 500 }}>
            {t('serviceFlow.previousVariables.dateAndTime.time')}
          </label>
          <FormCheckbox
            label=""
            name="timePrecision"
            hideLabel
            item={{
              label: String(t('serviceFlow.previousVariables.dateAndTime.setTime')),
              value: 'setTime',
            }}
            checked={isTimePrecisionEnabled}
            onChange={() => setIsTimePrecisionEnabled(!isTimePrecisionEnabled)}
          />
          {isTimePrecisionEnabled && (
            <FormInput
              label={String(t('serviceFlow.previousVariables.dateAndTime.time'))}
              name="timeFormat"
              type="text"
              value={time}
              onChange={(e) => setTime(e.target.value)}
              placeholder="HH:mm:ss.SSS"
              style={{ width: '100%', maxWidth: '100%' }}
            />
          )}

          <label style={{ fontSize: '14px', fontWeight: 500 }}>
            {t('serviceFlow.previousVariables.dateAndTime.output')}
          </label>
        </Track>

        <Track direction="vertical" align="stretch" gap={16} style={{ flex: '0 0 50%', maxWidth: '50%' }}>
          <label style={{ fontSize: '14px', fontWeight: 500 }}>
            {t('serviceFlow.previousVariables.dateAndTime.format')}
          </label>

          <FormSelect
            label=""
            name="formatType"
            hideLabel
            options={[
              { label: String(t('serviceFlow.previousVariables.dateAndTime.dateOnly')), value: 'dateOnly' },
              { label: String(t('serviceFlow.previousVariables.dateAndTime.timestamp')), value: 'timestamp' },
              { label: String(t('serviceFlow.previousVariables.dateAndTime.timestampMs')), value: 'timestampMs' },
              { label: String(t('serviceFlow.previousVariables.dateAndTime.yearOnly')), value: 'yearOnly' },
              { label: String(t('serviceFlow.previousVariables.dateAndTime.custom')), value: 'custom' },
            ]}
            defaultValue={formatType}
            style={{ fontSize: '14px', width: '100%', maxWidth: '100%' }}
            onSelectionChange={(selection) => {
              if (selection) {
                setFormatType(selection.value as FormatType);
              }
            }}
          />

          {(formatType === 'dateOnly' ||
            formatType === 'custom' ||
            formatType === 'timestamp' ||
            formatType === 'timestampMs') && (
            <>
              <label style={{ fontSize: '14px', fontWeight: 500 }}>
                {t('serviceFlow.previousVariables.dateAndTime.dateOrder')}
              </label>
              <Track direction="horizontal" align="stretch" gap={8}>
                {[0, 1, 2].map((index) => {
                  const handleDateOrderChange = (newValue: DatePart) => {
                    const newOrder: [DatePart, DatePart, DatePart] = [...dateOrder];
                    const currentValue = dateOrder[index];

                    // If the new value is already in another position, swap them
                    const existingIndex = dateOrder.findIndex((val) => val === newValue);
                    if (existingIndex !== -1 && existingIndex !== index) {
                      newOrder[existingIndex] = currentValue;
                    }

                    newOrder[index] = newValue;
                    setDateOrder(newOrder);
                  };

                  return (
                    <FormSelect
                      key={index}
                      label=""
                      name={`dateOrder${index + 1}`}
                      hideLabel
                      options={['YYYY', 'MM', 'DD'].map((part) => ({ label: part, value: part }))}
                      defaultValue={dateOrder[index]}
                      style={{ fontSize: '14px', width: '100%', maxWidth: '100%' }}
                      onSelectionChange={(selection) => {
                        if (selection) {
                          handleDateOrderChange(selection.value as DatePart);
                        }
                      }}
                    />
                  );
                })}
              </Track>

              <label style={{ fontSize: '14px', fontWeight: 500 }}>
                {t('serviceFlow.previousVariables.dateAndTime.separator')}
              </label>
              <FormSelect
                label=""
                name="separator"
                hideLabel
                options={[
                  { label: '.', value: '.' },
                  { label: '/', value: '/' },
                  { label: '-', value: '-' },
                ]}
                defaultValue={separator}
                style={{ fontSize: '14px', width: '100%', maxWidth: '100%' }}
                onSelectionChange={(selection) => {
                  if (selection) {
                    setSeparator(selection.value as Separator);
                  }
                }}
              />
            </>
          )}
        </Track>
      </Track>
    </Track>
  );
};

export default DateTimeBuilder;
