prepare_step:
  assign:
    headers: ""
    body: ""
    params: ""
combine_step:
  assign:
    sensitive: ${new Map([["headers", headers], ["body", body], ["params", params]])}
return_value:
  wrapper: false
  return: ${sensitive}
