version: '3.9'
services:
  ruuter:
    container_name: pipelines
    environment:
      - OPENSEARCH_PROTOCOL=http
    build:
      context: .
    ports:
      - 3010:3010
    networks:
      - bykstack

networks:
  bykstack:
    driver: bridge
#    external: true
